### ISSUE TITLE
Trees page doesn't delete last node

### ISSUE THREAD

**Issue by JayThomason** [pierce-m/pierce-m.github.io#1]
Steps to reproduce:
1. go to /trees
2. select binary search tree
3. enter a number in the insert box (e.g. 1234)
4. press enter
5. enter same number in the delete box (e.g. 1234).

Note that the node is not actually removed from the page. It seems like the update just isn't being drawn to the canvas because as soon as you insert another number it just takes the place of the previous number in the first node.

**Comment by pierce-m** [comment]
Took me a while to get to this, but the bug is now fixed, thanks. In the future, please report a project's bugs to its respective repository, in this case https://github.com/pierce-m/trees.
